openapi: "3.0.2"
info:
  title: Expense management
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /expense/list:
    post:
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'

components:
  schemas:
    Expense:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: "Продукты питания"
