version: '3.9'

name: my-expenses

services:
  app:
    build: ./
    restart: always
    ports:
      - 8000:8080
    depends_on: 
      - db
    environment:
      - MYURL=postgres://expense_user:zorro@db:5432/expenses?sslmode=disable
      - DB_PASSWORD=zorro
    


  db:
    image: postgres:14.11
    restart: always
    environment:
      - POSTGRES_PASSWORD=zorro
      - POSTGRES_USER=expense_user
      - POSTGRES_DB=expenses

    ports:
      - 5436:5432  

    container_name: postgres_exp
