version: '3.9'
services:
  app1:
    build: ./
   
    ports:
      - 8000:8080
    depends_on: 
      - db
    environment:
      - MYURL1=postgres://expense_user:zorro@db:5432/expenses?sslmode=disable
      - DB_PASSWORD=zorro
    


  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=zorro
      - POSTGRES_USER=expense_user
      - POSTGRES_DB=expenses

    ports:
      - 5436:5432  
    volumes:
      - /home/denis/projects/expense_db:/var/lib/postgresql/data
    container_name: postgres_exp
