version: '3.8'
services:
  app1:
    build: ./
    command: ./expenses
    ports:
      - 8080:8080
    depends_on: 
      - db
    environment:
      - MYURL=postgres://expense_user:zorro@db:5432/expenses
      - DB_PASSWORD=zorro


  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=zorro
    ports:
      - 5436:5432  
    volumes:
      - expense:/var/lib/postgresql/data

volumes:
  expense: