openapi: 3.0.0
info:
  title: File Upload API
  version: 1.0.0
paths:
  /expense/upload/:
    post:
      summary: Загрузка файла
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Файл для загрузки (doc, pdf, txt)
                expenseID:
                  type: integer
                  description: Идентификатор расхода
      responses:
        '200':
          description: Файл успешно загружен
        '400':
          description: Неверный запрос
